### ISSUE TITLE
IE11でformat時にgが効かず、nが西暦となる

### ISSUE THREAD

**Issue by nobokoba** [yukik/koyomi#4]
Chrome

```
koyomi.format(new Date(), "gn/M/D")
> "H28/5/12"
```

IE11

```
koyomi.format(new Date(), "gn/M/D")
> "2016/5/12"
```

**Comment by yukik** [comment]
今、手元にIEの環境がないため、最後まで確認できていないのですが
おそらくfor(var x of y) 構文がIE11でサポートされていないのでfor(var i =0; i <len; i++)に変更すれば大丈夫だと思います

修正したファイルはlib/utils/getEra.jsです

古いブラウザでのテストは、example/test/test.htmlをそのブラウザで開くことで確認できるようになっています

**Comment by nobokoba** [comment]
同様の現象が発生するようです。IE11では`Date`のコンストラクタが`lib/config.js`内に記載されているフォーマット`'1989-01-08 00:00:00.000'`形式に対応していないようです。

ISO 8601のフォーマットであれば上手くパース出来ましたので、ISO 8601へ変更したPRを作成しました。

**Comment by yukik** [comment]
返事がたいへん遅くなってしまいすいません。
すいません。PRをマージする前に改元のPRを先にしてしまい、競合してしまいました。
再度お願いしてもよろしいでしょうか

**Comment by nobokoba** [comment]
再度PRを作成しました。よろしくお願いします。

**Comment by yukik** [comment]
PRありがとうございます。

**Comment by nobokoba** [comment]
PRのマージありがとうございます！
